export const GET_SEASONS_SUCCESS = "GET_SEASONS_SUCCESS";
export const GET_SEASON_QUALIFYING_POLES_SUCCESS =
  "GET_SEASON_QUALIFYING_POLES_SUCCESS";
export const SET_QUALIFYING_SEASON = "SET_QUALIFYING_SEASON";

export const GET_CIRCUIT_QUALIFYING_RESULTS_SUCCESS =
  "GET_CIRCUIT_QUALIFYING_RESULTS_SUCCESS";

export const GET_CIRCUIT_INFORMATION_SUCCESS =
  "GET_CIRCUIT_INFORMATION_SUCCESS";



export const GET_RACE_RESULT_SUCCESS = "GET_RACE_RESULT_SUCCESS";
export const GET_RACE_SCHEDULE_SUCCESS = "GET_RACE_SCHEDULE_SUCCESS";
