export const SET_QUALIFYING_SEASONS = "SET_QUALIFYING_SEASONS";
export const SET_SEASON_QUALIFYING_POLES =
  "SET_SEASON_QUALIFYING_POLES";
export const SET_QUALIFYING_SEASON = "SET_QUALIFYING_SEASON";

export const SET_CIRCUIT_QUALIFYING_RESULTS =
  "SET_CIRCUIT_QUALIFYING_RESULTS";

export const SET_CIRCUIT_INFORMATION =
  "GET_CIRCUIT_INFORMSET_CIRCUIT_INFORMATIONATION_SUCCESS";

export const SET_RACE_RESULT = "SET_RACE_RESULT";
export const SET_RACE_SCHEDULE = "SET_RACE_SCHEDULE";
